language: node_js
node_js:
  - "8"
cache: yarn

addons:
  sauce_connect:
    - username: "TPWDWr9Q4RKnmcedtQRIkrlOZHkPATXAnidJVR6AygtTmjPPwFwkJ6631/oxIQk8wMXUPCKHd7DyVINO36ael4DH4YV/7Vc4kMeTD106BS4MSCDfQnX8aaG3g/78cverb8R56hNt9qUCLhmQZCbEYBAEndC+g2indAAlnFyRFYdqfiW7jO0A+ucqPu25b//0K0JAI6IHoPC5nFy/zB1aCjt5NqBh/oDm6ao5NeHNFjdV9HwPsw3/zEMJljMCNdQ5byib47rEU7lNTBw+CHcAeOf4HMi8lrPqJFqV1LT5fB2qvBikEH1LPKjZbI9r3xw57Ja5cRjmaujyxZ10lGm3EAnJtt0kFZkuD78dVu8RVuDyK8owsi9fy8R5miDDJ3t3kX2Ia+YNSXFa60vL5YfQCNN/0aDqvBeOgHz26+/0lnl47rtlhfVpGyP0/Lu/3Ni7HRGRujCx+wxmfWSvHMNX3qKEahj30HmHdwlOjeAZGc9PtGlTEEv+LqbjGuBHeQlUwy8TXNhbq7BD6ja51Jc66e7NtHGnQmWN4zqZLtTXGNfWsmTOBiS5W/V55SziutXlYzQv/0YfvAnXXR0zLnNoODptqct9UvJdk2dN0aA3Ij0NeIDhi6bSiFbj+pX5LgKCZ4DA13Mus92lmNDX02uLPNA8RvFB9KKZHdS+xyCrUdQ="
    - access_key: "N4E31x6tD92nYHAtykz4Ca16zwmPQath9AWPAehPa7OJvv+1CPDl08QghWx5f53ft9pqt+oqRBGDGLZiL/X3aguFGlQSHkkeD/ORfNjsEL0hso3c6rS8tifAJjyPAEXDl8E1IbNtgRandv5SLAakJz/jBsKSbNsDYjJfQPv3PxPT9lezQe/eAijyDnbETdnyKk0Yof1WjLxbSafyRY+ugrxbhspdDRk6rWaMFBIDCJc6f29Fyt3//Codv2rUHluh7+G9pMJvrmis18gqYCYg2+NuUEHE2oQonwReaRqYyWU8fhKXGIR3stfbuPJcByR4MtfYp9yhmcjokr+xteQOtBb/bJ3c3QfN/VJumqEL+Adq26nYfYxsh4niGK2G0x7t28GIrPQE6yWxkY7IB4+1eSXTsLxvpbvqwqjhAjmXnNu1oXSw5nxMzeKaHWczP//iWBkTBkhapH/hq169AYDHu7zI8wXnS4ZPNtoDHkuh13gU1SHsAMhpm7H9sm2hCFsWMYhx+aA/gTX/bhcib8TMYnf1wcvmnjAnKLP93pJpBha5xxVsB4/ZXLAQEiYjvzmVt+v9KsQl6+KaorOpo2v/ecwoGBL3eHHcGyyIa7JzvcZ5XkE62PONJZPpgPOkNDjSncQXNrJfmQFhm5gKjmFv+rcoMBPETZPlX0ne1njACxs="

before_script:
  - yarn serve &
